import { InspirationCard } from "./types";

// The Discover feed. Every card except the clearly-labelled "idea only" one
// is backed by real source_package_ids from mockInventory.ts.

export const INSPIRATION_CARDS: InspirationCard[] = [
  {
    card_id: "CARD_001",
    headline: "Golden-hour dinners.\nNo crowds.",
    destination_id: "DEST_CHANIA",
    destination_name: "Chania",
    country: "Greece",
    media_url: "https://picsum.photos/seed/chania-harbour/900/1400",
    vibe_tags: ["warm evenings", "great food", "no crowds"],
    inventory_status: "available",
    lowest_price_pp: 820,
    currency: "GBP",
    source_package_ids: ["PKG_009", "PKG_022"],
    moods: { romance: 0.8, food: 0.7, relaxation: 0.6 },
  },
  {
    card_id: "CARD_002",
    headline: "Warm water. Bare feet.\nNothing scheduled.",
    destination_id: "DEST_MENORCA",
    destination_name: "Menorca",
    country: "Spain",
    media_url: "https://picsum.photos/seed/menorca-cove/900/1400",
    vibe_tags: ["warm water", "quiet", "no plans"],
    inventory_status: "available",
    lowest_price_pp: 1100,
    currency: "GBP",
    source_package_ids: ["PKG_005"],
    moods: { relaxation: 0.9, romance: 0.6 },
  },
  {
    card_id: "CARD_003",
    headline: "Electric nights.\nSleep late.",
    destination_id: "DEST_IBIZA",
    destination_name: "Ibiza",
    country: "Spain",
    media_url: "https://picsum.photos/seed/ibiza-sunset/900/1400",
    vibe_tags: ["nightlife", "adult-only", "sunsets"],
    inventory_status: "available",
    lowest_price_pp: 980,
    currency: "GBP",
    source_package_ids: ["PKG_017"],
    moods: { nightlife: 0.7, romance: 0.5 },
  },
  {
    card_id: "CARD_004",
    headline: "Food markets. Old streets.\nSea air.",
    destination_id: "DEST_PALERMO",
    destination_name: "Palermo",
    country: "Italy",
    media_url: "https://picsum.photos/seed/palermo-palazzo/900/1400",
    vibe_tags: ["food markets", "old streets", "sea air"],
    inventory_status: "available",
    lowest_price_pp: 780,
    currency: "GBP",
    source_package_ids: ["PKG_007", "PKG_008"],
    moods: { culture: 0.9, food: 0.9 },
  },
  {
    card_id: "CARD_005",
    headline: "Peaceful but\nnot boring.",
    destination_id: "DEST_IBIZA",
    destination_name: "Ibiza (North Coast)",
    country: "Spain",
    media_url: "https://picsum.photos/seed/ibiza-north/900/1400",
    vibe_tags: ["quiet", "boutique", "not resorty"],
    inventory_status: "available",
    lowest_price_pp: 1150,
    currency: "GBP",
    source_package_ids: ["PKG_018"],
    moods: { relaxation: 0.7, romance: 0.6, wellness: 0.4 },
  },
  {
    card_id: "CARD_006",
    headline: "Big landscapes.\nSmall hotels.",
    destination_id: "DEST_MADEIRA",
    destination_name: "Madeira",
    country: "Portugal",
    media_url: "https://picsum.photos/seed/madeira-levada/900/1400",
    vibe_tags: ["hiking", "big views", "small hotel"],
    inventory_status: "available",
    lowest_price_pp: 870,
    currency: "GBP",
    source_package_ids: ["PKG_011", "PKG_012"],
    moods: { adventure: 0.9, wellness: 0.6 },
  },
  {
    card_id: "CARD_007",
    headline: "Culture without\nmuseums all day.",
    destination_id: "DEST_DUBROVNIK",
    destination_name: "Dubrovnik",
    country: "Croatia",
    media_url: "https://picsum.photos/seed/dubrovnik-oldtown/900/1400",
    vibe_tags: ["old streets", "history", "romantic"],
    inventory_status: "available",
    lowest_price_pp: 890,
    currency: "GBP",
    source_package_ids: ["PKG_015", "PKG_016", "PKG_024"],
    moods: { culture: 0.8, romance: 0.7 },
  },
  {
    card_id: "CARD_008",
    headline: "Adult-only.\nWarm evenings. Good food.",
    destination_id: "DEST_PUGLIA",
    destination_name: "Puglia",
    country: "Italy",
    media_url: "https://picsum.photos/seed/puglia-trulli/900/1400",
    vibe_tags: ["adult-only", "warm evenings", "good food"],
    inventory_status: "available",
    lowest_price_pp: 892,
    currency: "GBP",
    source_package_ids: ["PKG_001", "PKG_021"],
    moods: { food: 0.9, romance: 0.6, culture: 0.6 },
  },
  {
    card_id: "CARD_009",
    headline: "Tapas after dark.\nBeach before lunch.",
    destination_id: "DEST_VALENCIA",
    destination_name: "Valencia",
    country: "Spain",
    media_url: "https://picsum.photos/seed/valencia-ruzafa/900/1400",
    vibe_tags: ["good food", "electric nights", "city + beach"],
    inventory_status: "available",
    lowest_price_pp: 495,
    currency: "GBP",
    source_package_ids: ["PKG_013", "PKG_014", "PKG_023"],
    moods: { food: 0.8, nightlife: 0.6, culture: 0.7 },
  },
  {
    card_id: "CARD_010",
    headline: "Temple gardens.\nQuiet lanes at dusk.",
    destination_id: "DEST_KYOTO",
    destination_name: "Kyoto",
    country: "Japan",
    media_url: "https://picsum.photos/seed/kyoto-lanes/900/1400",
    vibe_tags: ["culture", "quiet", "not on sale here"],
    inventory_status: "idea_only",
    lowest_price_pp: null,
    currency: "GBP",
    source_package_ids: [],
    moods: { culture: 0.9, relaxation: 0.5, wellness: 0.4 },
  },
];
