import { InventoryPackage, MoodScores } from "./types";

// Mock inventory — stands in for a real supplier/inventory API.
// This is the ONLY source of truth for price, dates, flights, availability.
// The LLM is never allowed to invent any field in this file.

function moods(partial: Partial<MoodScores>): MoodScores {
  return {
    adventure: 0.2,
    relaxation: 0.4,
    culture: 0.3,
    food: 0.3,
    nightlife: 0.1,
    romance: 0.3,
    wellness: 0.2,
    ...partial,
  };
}

function img(seed: string) {
  return `https://picsum.photos/seed/${seed}/900/1400`;
}

export const INVENTORY: InventoryPackage[] = [
  // --- Puglia, Italy ---
  {
    package_id: "PKG_001",
    destination_id: "DEST_PUGLIA",
    hotel_id: "HOTEL_PUGLIA_MASSERIA",
    destination_name: "Puglia",
    country: "Italy",
    hotel_name: "Masseria near Ostuni",
    hotel_type: "boutique",
    adult_only: false,
    departure_airport: "LGW",
    departure_date: "2026-09-12",
    return_date: "2026-09-19",
    nights: 7,
    flight_duration_minutes: 250,
    price_pp: 892,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 4,
    board_basis: "B&B",
    image_url: img("puglia-masseria"),
    booking_url: "https://example.com/book/PKG_001",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_001",
    avg_temp_c: 28,
    moods: moods({ food: 0.9, culture: 0.7, relaxation: 0.7, romance: 0.6, nightlife: 0.1 }),
    description: "Stay in a restored masseria near beaches. Big on food.",
    vibe_tags: ["warm evenings", "good food", "old streets", "boutique hotel"],
  },
  {
    package_id: "PKG_002",
    destination_id: "DEST_PUGLIA",
    hotel_id: "HOTEL_PUGLIA_RESORT",
    destination_name: "Puglia",
    country: "Italy",
    hotel_name: "Ostuni Beach Resort",
    hotel_type: "resort",
    adult_only: false,
    departure_airport: "LGW",
    departure_date: "2026-09-05",
    return_date: "2026-09-12",
    nights: 7,
    flight_duration_minutes: 245,
    price_pp: 749,
    currency: "GBP",
    availability_status: "limited",
    rooms_remaining: 2,
    board_basis: "Half board",
    image_url: img("puglia-resort"),
    booking_url: "https://example.com/book/PKG_002",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_002",
    avg_temp_c: 27,
    moods: moods({ food: 0.6, relaxation: 0.7, culture: 0.3, nightlife: 0.2 }),
    description: "Family-friendly beach resort with pools and a private cove.",
    vibe_tags: ["warm sea", "family friendly", "pools"],
  },

  // --- Lisbon, Portugal ---
  {
    package_id: "PKG_003",
    destination_id: "DEST_LISBON",
    hotel_id: "HOTEL_LISBON_BOUTIQUE",
    destination_name: "Lisbon",
    country: "Portugal",
    hotel_name: "Alfama Boutique Townhouse",
    hotel_type: "boutique",
    adult_only: true,
    departure_airport: "LGW",
    departure_date: "2026-09-10",
    return_date: "2026-09-14",
    nights: 4,
    flight_duration_minutes: 165,
    price_pp: 640,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 6,
    board_basis: "Room only",
    image_url: img("lisbon-alfama"),
    booking_url: "https://example.com/book/PKG_003",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_001",
    avg_temp_c: 25,
    moods: moods({ culture: 0.9, food: 0.8, nightlife: 0.5, adventure: 0.3, relaxation: 0.2 }),
    description: "Old-town townhouse steps from tiled streets and tascas.",
    vibe_tags: ["old streets", "good food", "city energy"],
  },
  {
    package_id: "PKG_004",
    destination_id: "DEST_LISBON",
    hotel_id: "HOTEL_LISBON_RIVER",
    destination_name: "Lisbon",
    country: "Portugal",
    hotel_name: "Tagus Riverside Hotel",
    hotel_type: "city",
    adult_only: false,
    departure_airport: "STN",
    departure_date: "2026-09-18",
    return_date: "2026-09-22",
    nights: 4,
    flight_duration_minutes: 170,
    price_pp: 585,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 9,
    board_basis: "B&B",
    image_url: img("lisbon-river"),
    booking_url: "https://example.com/book/PKG_004",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_003",
    avg_temp_c: 25,
    moods: moods({ culture: 0.7, food: 0.7, nightlife: 0.6, relaxation: 0.2 }),
    description: "Modern riverside base for tram rides and pastel de nata crawls.",
    vibe_tags: ["city break", "good food", "electric nights"],
  },

  // --- Menorca, Spain ---
  {
    package_id: "PKG_005",
    destination_id: "DEST_MENORCA",
    hotel_id: "HOTEL_MENORCA_COVE",
    destination_name: "Menorca",
    country: "Spain",
    hotel_name: "Cala Boutique Cove Hotel",
    hotel_type: "boutique",
    adult_only: true,
    departure_airport: "LGW",
    departure_date: "2026-09-08",
    return_date: "2026-09-15",
    nights: 7,
    flight_duration_minutes: 155,
    price_pp: 1100,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 3,
    board_basis: "B&B",
    image_url: img("menorca-cove"),
    booking_url: "https://example.com/book/PKG_005",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_002",
    avg_temp_c: 27,
    moods: moods({ relaxation: 0.9, romance: 0.6, food: 0.4, culture: 0.3, nightlife: 0.1 }),
    description: "Quiet cove-side stay with turquoise water and little else.",
    vibe_tags: ["warm water", "quiet", "no crowds"],
  },
  {
    package_id: "PKG_006",
    destination_id: "DEST_MENORCA",
    hotel_id: "HOTEL_MENORCA_FAMILY",
    destination_name: "Menorca",
    country: "Spain",
    hotel_name: "Playa Family Resort",
    hotel_type: "family",
    adult_only: false,
    departure_airport: "LHR",
    departure_date: "2026-09-01",
    return_date: "2026-09-08",
    nights: 7,
    flight_duration_minutes: 160,
    price_pp: 799,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 12,
    board_basis: "All inclusive",
    image_url: img("menorca-family"),
    booking_url: "https://example.com/book/PKG_006",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_003",
    avg_temp_c: 27,
    moods: moods({ relaxation: 0.7, food: 0.3, culture: 0.1, nightlife: 0.2 }),
    description: "All-inclusive family resort with kids' club and water park.",
    vibe_tags: ["family friendly", "all inclusive", "pools"],
  },

  // --- Palermo, Sicily, Italy ---
  {
    package_id: "PKG_007",
    destination_id: "DEST_PALERMO",
    hotel_id: "HOTEL_PALERMO_PALAZZO",
    destination_name: "Palermo",
    country: "Italy",
    hotel_name: "Restored Palazzo near the markets",
    hotel_type: "boutique",
    adult_only: true,
    departure_airport: "LGW",
    departure_date: "2026-09-14",
    return_date: "2026-09-19",
    nights: 5,
    flight_duration_minutes: 195,
    price_pp: 780,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 5,
    board_basis: "B&B",
    image_url: img("palermo-palazzo"),
    booking_url: "https://example.com/book/PKG_007",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_001",
    avg_temp_c: 29,
    moods: moods({ culture: 0.9, food: 0.9, adventure: 0.4, nightlife: 0.3, relaxation: 0.2 }),
    description: "Street food markets, baroque churches and sea air, no crowds.",
    vibe_tags: ["food markets", "old streets", "sea air"],
  },
  {
    package_id: "PKG_008",
    destination_id: "DEST_PALERMO",
    hotel_id: "HOTEL_PALERMO_COAST",
    destination_name: "Palermo",
    country: "Italy",
    hotel_name: "Mondello Coast Hotel",
    hotel_type: "resort",
    adult_only: false,
    departure_airport: "STN",
    departure_date: "2026-09-20",
    return_date: "2026-09-27",
    nights: 7,
    flight_duration_minutes: 200,
    price_pp: 910,
    currency: "GBP",
    availability_status: "limited",
    rooms_remaining: 2,
    board_basis: "Half board",
    image_url: img("palermo-coast"),
    booking_url: "https://example.com/book/PKG_008",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_002",
    avg_temp_c: 28,
    moods: moods({ relaxation: 0.6, food: 0.6, culture: 0.5, nightlife: 0.2 }),
    description: "Beachfront in Mondello with the old city a short ride away.",
    vibe_tags: ["warm sea", "good food", "beach"],
  },

  // --- Chania, Crete, Greece ---
  {
    package_id: "PKG_009",
    destination_id: "DEST_CHANIA",
    hotel_id: "HOTEL_CHANIA_HARBOUR",
    destination_name: "Chania",
    country: "Greece",
    hotel_name: "Old Harbour Boutique Hotel",
    hotel_type: "adult-only",
    adult_only: true,
    departure_airport: "LGW",
    departure_date: "2026-09-12",
    return_date: "2026-09-19",
    nights: 7,
    flight_duration_minutes: 235,
    price_pp: 950,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 4,
    board_basis: "B&B",
    image_url: img("chania-harbour"),
    booking_url: "https://example.com/book/PKG_009",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_003",
    avg_temp_c: 27,
    moods: moods({ romance: 0.8, culture: 0.7, food: 0.7, relaxation: 0.6, nightlife: 0.2 }),
    description: "Venetian harbour views, tavernas, and evenings that slow right down.",
    vibe_tags: ["golden-hour dinners", "no crowds", "adult-only"],
  },
  {
    package_id: "PKG_010",
    destination_id: "DEST_CHANIA",
    hotel_id: "HOTEL_CHANIA_VILLAS",
    destination_name: "Chania",
    country: "Greece",
    hotel_name: "Akrotiri Cliffside Villas",
    hotel_type: "boutique",
    adult_only: true,
    departure_airport: "LHR",
    departure_date: "2026-09-06",
    return_date: "2026-09-13",
    nights: 7,
    flight_duration_minutes: 240,
    price_pp: 1180,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 3,
    board_basis: "B&B",
    image_url: img("chania-villas"),
    booking_url: "https://example.com/book/PKG_010",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_001",
    avg_temp_c: 27,
    moods: moods({ romance: 0.9, relaxation: 0.8, wellness: 0.5, food: 0.5, culture: 0.4 }),
    description: "Private-pool villas on the cliffs above the Aegean.",
    vibe_tags: ["quiet", "sea view", "romantic"],
  },

  // --- Madeira, Portugal ---
  {
    package_id: "PKG_011",
    destination_id: "DEST_MADEIRA",
    hotel_id: "HOTEL_MADEIRA_LEVADA",
    destination_name: "Madeira",
    country: "Portugal",
    hotel_name: "Levada Trail Lodge",
    hotel_type: "boutique",
    adult_only: false,
    departure_airport: "LGW",
    departure_date: "2026-09-09",
    return_date: "2026-09-16",
    nights: 7,
    flight_duration_minutes: 235,
    price_pp: 870,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 7,
    board_basis: "B&B",
    image_url: img("madeira-levada"),
    booking_url: "https://example.com/book/PKG_011",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_002",
    avg_temp_c: 24,
    moods: moods({ adventure: 0.9, wellness: 0.6, relaxation: 0.5, culture: 0.3, nightlife: 0.05 }),
    description: "Base for cliff-edge hiking trails and volcanic swimming pools.",
    vibe_tags: ["big landscapes", "small hotel", "hiking"],
  },
  {
    package_id: "PKG_012",
    destination_id: "DEST_MADEIRA",
    hotel_id: "HOTEL_MADEIRA_SPA",
    destination_name: "Madeira",
    country: "Portugal",
    hotel_name: "Funchal Wellness Retreat",
    hotel_type: "adult-only",
    adult_only: true,
    departure_airport: "STN",
    departure_date: "2026-09-21",
    return_date: "2026-09-28",
    nights: 7,
    flight_duration_minutes: 240,
    price_pp: 1040,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 5,
    board_basis: "Half board",
    image_url: img("madeira-spa"),
    booking_url: "https://example.com/book/PKG_012",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_003",
    avg_temp_c: 24,
    moods: moods({ wellness: 0.9, relaxation: 0.8, romance: 0.4, culture: 0.2, nightlife: 0.05 }),
    description: "Clifftop spa retreat with ocean pools, adults only.",
    vibe_tags: ["peaceful", "wellness", "adult-only"],
  },

  // --- Valencia, Spain ---
  {
    package_id: "PKG_013",
    destination_id: "DEST_VALENCIA",
    hotel_id: "HOTEL_VALENCIA_RUZAFA",
    destination_name: "Valencia",
    country: "Spain",
    hotel_name: "Ruzafa Design Hotel",
    hotel_type: "boutique",
    adult_only: true,
    departure_airport: "LGW",
    departure_date: "2026-09-11",
    return_date: "2026-09-15",
    nights: 4,
    flight_duration_minutes: 145,
    price_pp: 560,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 8,
    board_basis: "Room only",
    image_url: img("valencia-ruzafa"),
    booking_url: "https://example.com/book/PKG_013",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_001",
    avg_temp_c: 28,
    moods: moods({ food: 0.8, culture: 0.7, nightlife: 0.6, adventure: 0.2, relaxation: 0.2 }),
    description: "Tapas-bar neighbourhood base, beach and city in one trip.",
    vibe_tags: ["good food", "city energy", "electric nights"],
  },
  {
    package_id: "PKG_014",
    destination_id: "DEST_VALENCIA",
    hotel_id: "HOTEL_VALENCIA_BEACH",
    destination_name: "Valencia",
    country: "Spain",
    hotel_name: "Malvarrosa Beach Hotel",
    hotel_type: "city",
    adult_only: false,
    departure_airport: "LHR",
    departure_date: "2026-09-16",
    return_date: "2026-09-20",
    nights: 4,
    flight_duration_minutes: 150,
    price_pp: 495,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 10,
    board_basis: "B&B",
    image_url: img("valencia-beach"),
    booking_url: "https://example.com/book/PKG_014",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_003",
    avg_temp_c: 28,
    moods: moods({ relaxation: 0.5, food: 0.6, culture: 0.5, nightlife: 0.4 }),
    description: "Easy beachfront stay a tram ride from the old town.",
    vibe_tags: ["warm sea", "good food", "city break"],
  },

  // --- Dubrovnik, Croatia ---
  {
    package_id: "PKG_015",
    destination_id: "DEST_DUBROVNIK",
    hotel_id: "HOTEL_DUBROVNIK_OLDTOWN",
    destination_name: "Dubrovnik",
    country: "Croatia",
    hotel_name: "Old Town Stone House",
    hotel_type: "boutique",
    adult_only: true,
    departure_airport: "LGW",
    departure_date: "2026-09-07",
    return_date: "2026-09-12",
    nights: 5,
    flight_duration_minutes: 165,
    price_pp: 890,
    currency: "GBP",
    availability_status: "limited",
    rooms_remaining: 2,
    board_basis: "B&B",
    image_url: img("dubrovnik-oldtown"),
    booking_url: "https://example.com/book/PKG_015",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_002",
    avg_temp_c: 26,
    moods: moods({ culture: 0.8, romance: 0.7, food: 0.5, relaxation: 0.4, nightlife: 0.2 }),
    description: "Stone-walled old town, city walls at sunrise, quiet by night.",
    vibe_tags: ["old streets", "culture without museums", "romantic"],
  },
  {
    package_id: "PKG_016",
    destination_id: "DEST_DUBROVNIK",
    hotel_id: "HOTEL_DUBROVNIK_CAVTAT",
    destination_name: "Dubrovnik",
    country: "Croatia",
    hotel_name: "Cavtat Waterfront Hotel",
    hotel_type: "resort",
    adult_only: false,
    departure_airport: "STN",
    departure_date: "2026-09-23",
    return_date: "2026-09-30",
    nights: 7,
    flight_duration_minutes: 170,
    price_pp: 1020,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 6,
    board_basis: "Half board",
    image_url: img("dubrovnik-cavtat"),
    booking_url: "https://example.com/book/PKG_016",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_003",
    avg_temp_c: 26,
    moods: moods({ relaxation: 0.7, culture: 0.5, food: 0.5, romance: 0.4 }),
    description: "Quieter waterfront town, 20 minutes from the old city walls.",
    vibe_tags: ["quiet", "warm sea", "no crowds"],
  },

  // --- Ibiza, Spain ---
  {
    package_id: "PKG_017",
    destination_id: "DEST_IBIZA",
    hotel_id: "HOTEL_IBIZA_ADULT",
    destination_name: "Ibiza",
    country: "Spain",
    hotel_name: "Adults-Only Sunset Hotel",
    hotel_type: "adult-only",
    adult_only: true,
    departure_airport: "LGW",
    departure_date: "2026-09-04",
    return_date: "2026-09-11",
    nights: 7,
    flight_duration_minutes: 150,
    price_pp: 980,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 5,
    board_basis: "B&B",
    image_url: img("ibiza-sunset"),
    booking_url: "https://example.com/book/PKG_017",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_001",
    avg_temp_c: 28,
    moods: moods({ nightlife: 0.7, romance: 0.5, relaxation: 0.4, food: 0.4 }),
    description: "West-coast sunset terraces, adults only, low-key by day.",
    vibe_tags: ["electric nights", "sleep late", "adult-only"],
  },
  {
    package_id: "PKG_018",
    destination_id: "DEST_IBIZA",
    hotel_id: "HOTEL_IBIZA_NORTH",
    destination_name: "Ibiza",
    country: "Spain",
    hotel_name: "North Coast Finca Stay",
    hotel_type: "boutique",
    adult_only: true,
    departure_airport: "LHR",
    departure_date: "2026-09-15",
    return_date: "2026-09-22",
    nights: 7,
    flight_duration_minutes: 155,
    price_pp: 1150,
    currency: "GBP",
    availability_status: "limited",
    rooms_remaining: 2,
    board_basis: "Room only",
    image_url: img("ibiza-north"),
    booking_url: "https://example.com/book/PKG_018",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_002",
    avg_temp_c: 28,
    moods: moods({ relaxation: 0.7, romance: 0.6, wellness: 0.4, nightlife: 0.2, culture: 0.2 }),
    description: "Rustic finca in the quiet north, far from the clubs.",
    vibe_tags: ["peaceful but not boring", "no crowds", "boutique"],
  },

  // --- Mallorca, Spain ---
  {
    package_id: "PKG_019",
    destination_id: "DEST_MALLORCA",
    hotel_id: "HOTEL_MALLORCA_SOLLER",
    destination_name: "Mallorca",
    country: "Spain",
    hotel_name: "Soller Valley Boutique Hotel",
    hotel_type: "boutique",
    adult_only: true,
    departure_airport: "LGW",
    departure_date: "2026-09-13",
    return_date: "2026-09-20",
    nights: 7,
    flight_duration_minutes: 150,
    price_pp: 940,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 4,
    board_basis: "B&B",
    image_url: img("mallorca-soller"),
    booking_url: "https://example.com/book/PKG_019",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_003",
    avg_temp_c: 27,
    moods: moods({ relaxation: 0.7, culture: 0.5, food: 0.6, adventure: 0.4, romance: 0.5 }),
    description: "Citrus-grove valley town, mountains on one side, sea on the other.",
    vibe_tags: ["big landscapes", "small hotel", "not too polished"],
  },
  {
    package_id: "PKG_020",
    destination_id: "DEST_MALLORCA",
    hotel_id: "HOTEL_MALLORCA_FAMILY",
    destination_name: "Mallorca",
    country: "Spain",
    hotel_name: "Alcudia Bay Family Resort",
    hotel_type: "family",
    adult_only: false,
    departure_airport: "STN",
    departure_date: "2026-09-02",
    return_date: "2026-09-09",
    nights: 7,
    flight_duration_minutes: 155,
    price_pp: 715,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 15,
    board_basis: "All inclusive",
    image_url: img("mallorca-alcudia"),
    booking_url: "https://example.com/book/PKG_020",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_001",
    avg_temp_c: 27,
    moods: moods({ relaxation: 0.6, food: 0.3, nightlife: 0.2, culture: 0.1 }),
    description: "Long sandy bay, all-inclusive, built for families.",
    vibe_tags: ["family friendly", "all inclusive", "warm sea"],
  },

  // --- extra Puglia + Chania late availability for depth ---
  {
    package_id: "PKG_021",
    destination_id: "DEST_PUGLIA",
    hotel_id: "HOTEL_PUGLIA_TRULLI",
    destination_name: "Puglia",
    country: "Italy",
    hotel_name: "Trulli Countryside Hideaway",
    hotel_type: "boutique",
    adult_only: true,
    departure_airport: "LHR",
    departure_date: "2026-09-19",
    return_date: "2026-09-26",
    nights: 7,
    flight_duration_minutes: 250,
    price_pp: 1010,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 3,
    board_basis: "B&B",
    image_url: img("puglia-trulli"),
    booking_url: "https://example.com/book/PKG_021",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_002",
    avg_temp_c: 28,
    moods: moods({ food: 0.8, relaxation: 0.7, romance: 0.6, culture: 0.5, nightlife: 0.05 }),
    description: "Converted trulli cones among olive groves, 20 minutes from the coast.",
    vibe_tags: ["peaceful but not boring", "good food", "boutique"],
  },
  {
    package_id: "PKG_022",
    destination_id: "DEST_CHANIA",
    hotel_id: "HOTEL_CHANIA_TOWN",
    destination_name: "Chania",
    country: "Greece",
    hotel_name: "Old Town Courtyard Rooms",
    hotel_type: "boutique",
    adult_only: false,
    departure_airport: "STN",
    departure_date: "2026-09-03",
    return_date: "2026-09-10",
    nights: 7,
    flight_duration_minutes: 245,
    price_pp: 820,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 6,
    board_basis: "B&B",
    image_url: img("chania-town"),
    booking_url: "https://example.com/book/PKG_022",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_003",
    avg_temp_c: 27,
    moods: moods({ culture: 0.7, food: 0.7, relaxation: 0.5, romance: 0.4 }),
    description: "Courtyard rooms behind the harbour, market stalls at the door.",
    vibe_tags: ["old streets", "food markets", "sea air"],
  },
  {
    package_id: "PKG_023",
    destination_id: "DEST_VALENCIA",
    hotel_id: "HOTEL_VALENCIA_ALBUFERA",
    destination_name: "Valencia",
    country: "Spain",
    hotel_name: "Albufera Lakeside Retreat",
    hotel_type: "boutique",
    adult_only: false,
    departure_airport: "LGW",
    departure_date: "2026-09-24",
    return_date: "2026-09-28",
    nights: 4,
    flight_duration_minutes: 145,
    price_pp: 610,
    currency: "GBP",
    availability_status: "sold_out",
    rooms_remaining: 0,
    board_basis: "B&B",
    image_url: img("valencia-albufera"),
    booking_url: "https://example.com/book/PKG_023",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_002",
    avg_temp_c: 27,
    moods: moods({ relaxation: 0.7, culture: 0.4, food: 0.5, wellness: 0.3 }),
    description: "Rice-paddy lake views, minutes from the city by bike.",
    vibe_tags: ["peaceful", "big landscapes", "no crowds"],
  },
  {
    package_id: "PKG_024",
    destination_id: "DEST_DUBROVNIK",
    hotel_id: "HOTEL_DUBROVNIK_LOKRUM",
    destination_name: "Dubrovnik",
    country: "Croatia",
    hotel_name: "Lokrum View Suites",
    hotel_type: "adult-only",
    adult_only: true,
    departure_airport: "LGW",
    departure_date: "2026-09-17",
    return_date: "2026-09-24",
    nights: 7,
    flight_duration_minutes: 165,
    price_pp: 1260,
    currency: "GBP",
    availability_status: "available",
    rooms_remaining: 3,
    board_basis: "B&B",
    image_url: img("dubrovnik-lokrum"),
    booking_url: "https://example.com/book/PKG_024",
    last_checked: "2026-06-30T18:45:00Z",
    supplier_id: "SUPPLIER_001",
    avg_temp_c: 26,
    moods: moods({ romance: 0.8, relaxation: 0.7, culture: 0.6, food: 0.5 }),
    description: "Sea-view suites looking out towards Lokrum island.",
    vibe_tags: ["romantic", "sea view", "adult-only"],
  },
];

export function getPackageById(id: string): InventoryPackage | undefined {
  return INVENTORY.find((p) => p.package_id === id);
}
